name: Test DNS Resolution

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test_dns:
    runs-on: ubuntu-latest
    steps:
      - name: Check DNS resolution
        run: nslookup fleettracker.pacificnational.com.au
