name: Refresh Token

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:    # manual trigger option

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd Tokens
          pip install -r requirements.txt

      - name: Run token refresh script
        run: |
          cd Tokens
          python app.py
