name: refresh_token

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour at minute 0
  workflow_dispatch:      # Allows manual triggering

jobs:
  refresh_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Tokens/requirements.txt

      - name: Show DNS resolution (debug)
        run: |
          nslookup fleettracker.pacificnational.com.au 8.8.8.8

      - name: Run token refresh script
        run: python Tokens/TokenRunner.py
