name: Token Refresh

on:
  schedule:
    - cron: '0 * * * *' # every hour at minute 0
  workflow_dispatch:

jobs:
  refresh_token:
    runs-on: ubuntu-latest

    env:
      # Force DNS resolution to use Google's public DNS
      RES_OPTIONS: 'nameserver 8.8.8.8'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Confirm DNS resolution via Google DNS
        run: nslookup fleettracker.pacificnational.com.au 8.8.8.8

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Tokens/requirements.txt

      - name: Run token refresh script
        run: python Tokens/TokenRunner.py

      - name: Confirm token file updated
        run: cat Tokens/token.json
